// Liste reelle des 50 villes actives en base (table villes, colonne code).
// Verifiee via psql le 24/07/2026 -- ne pas inventer de codes hors de
// cette liste, ils seraient rejetes par creerLigne (verification stricte
// cote backend contre la table villes).
export const VILLES: { code: string; nom: string }[] = [
  { code: 'abong-mbang', nom: 'Abong-Mbang' },
  { code: 'akonolinga', nom: 'Akonolinga' },
  { code: 'bafia', nom: 'Bafia' },
  { code: 'bafoussam', nom: 'Bafoussam' },
  { code: 'bali', nom: 'Bali' },
  { code: 'bamenda', nom: 'Bamenda' },
  { code: 'bandjoun', nom: 'Bandjoun' },
  { code: 'bangangte', nom: 'Bangangté' },
  { code: 'banyo', nom: 'Banyo' },
  { code: 'batouri', nom: 'Batouri' },
  { code: 'bertoua', nom: 'Bertoua' },
  { code: 'buea', nom: 'Buea' },
  { code: 'douala', nom: 'Douala' },
  { code: 'dschang', nom: 'Dschang' },
  { code: 'ebolowa', nom: 'Ebolowa' },
  { code: 'edea', nom: 'Édéa' },
  { code: 'eseka', nom: 'Eséka' },
  { code: 'foumban', nom: 'Foumban' },
  { code: 'garoua', nom: 'Garoua' },
  { code: 'garoua-boulai', nom: 'Garoua-Boulaï' },
  { code: 'guider', nom: 'Guider' },
  { code: 'kaele', nom: 'Kaélé' },
  { code: 'kousseri', nom: 'Kousséri' },
  { code: 'kribi', nom: 'Kribi' },
  { code: 'kumba', nom: 'Kumba' },
  { code: 'kumbo', nom: 'Kumbo' },
  { code: 'limbe', nom: 'Limbé' },
  { code: 'loum', nom: 'Loum' },
  { code: 'mamfe', nom: 'Mamfé' },
  { code: 'manjo', nom: 'Manjo' },
  { code: 'maroua', nom: 'Maroua' },
  { code: 'mbalmayo', nom: 'Mbalmayo' },
  { code: 'mbanga', nom: 'Mbanga' },
  { code: 'mbouda', nom: 'Mbouda' },
  { code: 'meiganga', nom: 'Meiganga' },
  { code: 'melong', nom: 'Melong' },
  { code: 'mfou', nom: 'Mfou' },
  { code: 'mokolo', nom: 'Mokolo' },
  { code: 'monatele', nom: 'Monatélé' },
  { code: 'mutengene', nom: 'Mutengene' },
  { code: 'ngaoundere', nom: 'Ngaoundéré' },
  { code: 'nkongsamba', nom: 'Nkongsamba' },
  { code: 'obala', nom: 'Obala' },
  { code: 'penja', nom: 'Penja' },
  { code: 'sangmelima', nom: 'Sangmélima' },
  { code: 'tibati', nom: 'Tibati' },
  { code: 'tiko', nom: 'Tiko' },
  { code: 'wum', nom: 'Wum' },
  { code: 'yagoua', nom: 'Yagoua' },
  { code: 'yaounde', nom: 'Yaoundé' },
];